// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myscqdjwenxyadjkfgbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15c2NxZGp3ZW54eWFkamtmZ2JjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MzIyOTAsImV4cCI6MjA2NDIwODI5MH0.y1EGNbjZCgK8BjJ6LcEBBS20qX-hMQ6fn4F3wTpqJio";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);